[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/impressum"
  to = "/impressum/index.html"
  status = 200

[[redirects]]
  from = "/datenschutz"
  to = "/datenschutz/index.html"
  status = 200

[[redirects]]
  from = "/storage"
  to = "/storage/index.html"
  status = 200

[[redirects]]
  from = "/parking"
  to = "/parking/index.html"
  status = 200

[[redirects]]
  from = "/service"
  to = "/service/index.html"
  status = 200

[[redirects]]
  from = "/keelcrab"
  to = "/keelcrab/index.html"
  status = 200

[[redirects]]
  from = "/kontakt"
  to = "/kontakt/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
